<<<<<<< HEAD
# Generated by Django 3.2.7 on 2021-09-08 23:53
=======
# Generated by Django 2.1.5 on 2019-01-15 14:05
>>>>>>> bbc966a9d58bf236d512eb56eb1ecf2ab5fc9f29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('name', models.CharField(max_length=140, verbose_name='circle name')),
                ('slug_name', models.SlugField(max_length=40, unique=True)),
                ('about', models.CharField(max_length=255, verbose_name='circle description')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='circles/pictures')),
                ('rides_offered', models.PositiveIntegerField(default=0)),
                ('rides_taken', models.PositiveIntegerField(default=0)),
                ('verified', models.BooleanField(default=False, help_text='Verified circles are also known as official communities.', verbose_name='verified circle')),
<<<<<<< HEAD
                ('is_public', models.BooleanField(default=True, help_text='Public circles are listed in the main page so everyone know about theire existence.')),
                ('is_limited', models.BooleanField(default=False, help_text='Limited circles can grow up to a fixed number of members.', verbose_name='limite')),
                ('members_limit', models.PositiveIntegerField(default=0, help_text='If circle is limited, this will be the maximum number of members.')),
=======
                ('is_public', models.BooleanField(default=True, help_text='Public circles are listed in the main page so everyone know about their existence.')),
                ('is_limited', models.BooleanField(default=False, help_text='Limited circles can grow up to a fixed number of members.', verbose_name='limited')),
                ('members_limit', models.PositiveIntegerField(default=0, help_text='If circle is limited, this will be the limit on the number of members.')),
>>>>>>> bbc966a9d58bf236d512eb56eb1ecf2ab5fc9f29
            ],
            options={
                'ordering': ['-rides_taken', '-rides_offered'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
